# Generated by Django 4.2.1 on 2023-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
